### ISSUE TITLE
Conflicting steps in https://azureossd.github.io/2020/08/07/wordpress-best-practices-for-performance/

### ISSUE THREAD

**Issue by yudomsft** [azureossd/azureossd.github.io#366]
I tried to follow the steps in [WordPress Best Practices for Performance
](https://azureossd.github.io/2020/08/07/wordpress-best-practices-for-performance/). However, I found that "Compressing Images" is incompatible with "Using Azure Blob Storage" because the Smush image compression plugin cannot handle files from an Azure storage account.

**Comment by Ajsalemo** [comment]
@chmald - FYI for the above blog post

**Comment by chmald** [comment]
Made updates to the page to indicate these are general steps.
If using Azure Blob Storage, I would recommend using W3 Total Cache. Those steps have been added.
