### ISSUE TITLE
error following https://azureossd.github.io/2020/05/05/debugging-php-application-on-azure-app-service-linux/index.html

### ISSUE THREAD

**Issue by edgreenberg** [azureossd/azureossd.github.io#79]
On the page https://azureossd.github.io/2020/05/05/debugging-php-application-on-azure-app-service-linux/index.html the instructions to build xdebug do not work.  

The command ```pecl install xdebug``` results in 
```
/tmp/pear/temp/xdebug/xdebug.c:18:10: fatal error: config.h: No such file or directory
 #include "config.h"
          ^~~~~~~~~~
compilation terminated.
```

The entire run is attached. 

I haven't been able to find any mention of this using search engines, nor is it reflected in pull requests here. 

[xdebug.failed.build.txt](https://github.com/azureossd/azureossd.github.io/files/7454420/xdebug.failed.build.txt)

**Comment by edgreenberg** [comment]
After posting this, I discovered that if I define PHP_ZENDEXTENSIONS as 'xdebug' I don't need to run the pecl install.  The xdebug.so just shows up. 

I realized that it was something like this, since /usr/local/lib/php/extensions wouldn't survive a reboot unless Azure took care of this.

**Comment by edisga** [comment]
Thanks for your feedback @edgreenberg.
@chmald can you validate it?

**Comment by chmald** [comment]
@edgreenberg @edisga 
Update the steps and branched out instructions for both using the platform image and a custom PHP container image.
